version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Expose frontend on port 3000
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Expose backend on port 5000
    networks:
      - app_network
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://database:27017/todo-list # Database connection string

  database:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo-data:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  mongo-data:

